# Generated by Django 4.1.7 on 2023-02-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tasks', '0004_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='serial_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='task-20230222172415', max_length=200),
        ),
    ]
