# Generated by Django 4.1.7 on 2023-02-22 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tasks', '0005_task_serial_id_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='customer_name',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('[+-/%]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='serial_id',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('[+-/%]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='task-20230222172942', max_length=200),
        ),
    ]
