# Generated by Django 4.1.7 on 2023-02-22 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tasks', '0006_remove_task_description_task_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('[+-/%]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='task-20230222174218', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
