# Generated by Django 4.1.7 on 2023-02-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tasks', '0009_task_time_zone_alter_task_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_zone',
            field=models.CharField(choices=[('utc', 'utc'), ('EST', 'est'), ('pst', 'pst'), ('cst', 'cst'), ('mst', 'mst'), ('hst', 'hst'), ('akst', 'akst')], default='cst', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='task-20230222182750', max_length=200),
        ),
    ]
